class Category_1005 {				
class MMT_Civ {	type = "trade_any_bicycle";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class Old_bike_TK_INS_EP1 {	type = "trade_any_bicycle";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class TT650_Civ {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class TT650_Ins {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class TT650_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class ATV_CZ_EP1 {	type = "trade_any_vehicle";	buy[] = {6,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class ATV_US_EP1 {	type = "trade_any_vehicle";	buy[] = {6,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class M1030_US_DES_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class Old_moto_TK_Civ_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class tractor {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class TowingTractor {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
};				
class Category_1006 {				
class Ikarus {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Ikarus_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class S1203_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {6,"ItemGoldBar"};	};
class S1203_ambulance_EP1 {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {6,"ItemGoldBar"};	};
};				
class Category_1007 {				
class Ural_CDF {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class Ural_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class Ural_UN_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class UralCivil_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class UralCivil2_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class V3S_Open_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {3,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class V3S_Open_TK_EP1 {	type = "trade_any_vehicle";	buy[] = {3,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class V3S_Civ {	type = "trade_any_vehicle";	buy[] = {3,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class V3S_RA_TK_GUE_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class V3S_TK_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Kamaz_DZE {	type = "trade_any_vehicle";	buy[] = {5,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class KamazOpen_DZE {	type = "trade_any_vehicle";	buy[] = {5,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class MTVR_DES_EP1 {	type = "trade_any_vehicle";	buy[] = {5,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class MTVR {	type = "trade_any_vehicle";	buy[] = {5,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
};				
class Category_1008 {				
class UralRefuel_TK_EP1_DZ {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class V3S_Refuel_TK_GUE_EP1_DZ {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class KamazRefuel_DZ {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class MtvrRefuel_DES_EP1_DZ {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class MtvrRefuel_DZ {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class MtvrRepair {	type = "trade_any_vehicle";	buy[] = {1,"ItemRuby"};	sell[] = {1,"ItemRuby"};	};
class V3S_Repair_TK_GUE_EP1 {	type = "trade_any_vehicle";	buy[] = {1,"ItemRuby"};	sell[] = {1,"ItemRuby"};	};
};				
class Category_1009 {				
class LandRover_CZ_EP1 {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class LandRover_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class HMMWV_M1035_DES_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class HMMWV_Ambulance {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class HMMWV_Ambulance_CZ_DES_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class HMMWV_DES_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class HMMWV_DZ {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class GAZ_Vodnik_MedEvac {	type = "trade_any_vehicle";	buy[] = {1,"ItemBriefcase100oz"};	sell[] = {4,"ItemGoldBar10oz"};	};
};				
class Category_1010 {				
class hilux1_civil_3_open_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class datsun1_civil_3_open_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class hilux1_civil_1_open_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class datsun1_civil_2_covered_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class datsun1_civil_1_open_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class hilux1_civil_2_covered_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
};				
class Category_1011 {				
class Skoda {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class SkodaBlue {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class SkodaGreen {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class SkodaRed {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class VolhaLimo_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class Volha_1_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class Volha_2_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class VWGolf {	type = "trade_any_vehicle";	buy[] = {5,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class car_hatchback {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class car_sedan {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class GLT_M300_LT {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class GLT_M300_ST {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class Lada1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class Lada1_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class Lada2 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class Lada2_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class LadaLM {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
};				
class Category_1012 {				
class SUV_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Blue {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Charcoal {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Green {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Orange {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Pink {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Red {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Silver {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_White {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Yellow {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class SUV_Camo {	type = "trade_any_vehicle";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class UAZ_CDF {	type = "trade_any_vehicle";	buy[] = {9,"ItemGoldBar"};	sell[] = {5,"ItemGoldBar"};	};
class UAZ_INS {	type = "trade_any_vehicle";	buy[] = {9,"ItemGoldBar"};	sell[] = {5,"ItemGoldBar"};	};
class UAZ_RU {	type = "trade_any_vehicle";	buy[] = {9,"ItemGoldBar"};	sell[] = {5,"ItemGoldBar"};	};
class UAZ_Unarmed_TK_CIV_EP1 {	type = "trade_any_vehicle";	buy[] = {9,"ItemGoldBar"};	sell[] = {5,"ItemGoldBar"};	};
class UAZ_Unarmed_TK_EP1 {	type = "trade_any_vehicle";	buy[] = {9,"ItemGoldBar"};	sell[] = {5,"ItemGoldBar"};	};
class UAZ_Unarmed_UN_EP1 {	type = "trade_any_vehicle";	buy[] = {9,"ItemGoldBar"};	sell[] = {5,"ItemGoldBar"};	};
};				
class Category_1013 {				
class Civcar {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Civcarbu {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class civcarbl {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Civcarre {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Civcarge {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Civcarwh {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Civcarsl {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_red {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_kiwi {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_black {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_silver {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_green {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_blue {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_gold {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_white {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_pink {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_mod {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_ruben {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_v {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_city {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class 350z_yellow {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
};				
				
class Category_1014 {				
class CVPI_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_Trooper_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_TrooperSL_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_NYPD_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_HighwaySL_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_UnmarkedB_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_UnmarkedG_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_LAPD_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_UnmarkedW_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_LAPDSL_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class CVPI_NYPDSL_Patrol {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class policecar {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class Copcar {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class Copcarhw {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
class Copcarswat {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar10oz"};	};
};				
