//{Loot_GROUP,		2,		pistols},
//{Loot_GROUP,		2,		shotgunsingleshot},
//{Loot_GROUP,		2,		farmweapons},
//{Loot_GROUP,		2,		sniperrifles},
//{Loot_GROUP,		2,		submachinegun},
//{Loot_GROUP,		2,		assaultrifles},
//{Loot_GROUP,		2,		militaryshotguns},
pistols[] = {
	{Loot_WEAPON,		2,		Makarov_DZ}, //Makarov
	{Loot_WEAPON,		2,		M1911_DZ}, //Colt1911
	{Loot_WEAPON,		1.5,	Revolver_DZ}, //revolver_EP1
	{Loot_WEAPON,		1,		G17_DZ}, //glock17_EP1
	{Loot_WEAPON,		1,		Makarov_SD_DZ}, //MakarovSD
	{Loot_WEAPON,		0.7,	M9_DZ}, //M9
	{Loot_WEAPON,		0.5,	M9_SD_DZ}, //M9SD
	{Loot_WEAPON,		0.1,	revolver_gold_EP1}
};
shotgunsingleshot[] = {
	{Loot_WEAPON,		2,		Winchester1866_DZ}, //Winchester1866
	{Loot_WEAPON,		1.7,	LeeEnfield_DZ}, //LeeEnfield
	{Loot_WEAPON,		1.7,	MR43_DZ}, //MR43
	{Loot_WEAPON,		1,		Saiga12K},
	{Loot_WEAPON,		1,		Remington870_DZ}, //Remington870_lamp
	{Loot_WEAPON,		1,		Crossbow_DZ},
	{Loot_WEAPON,		1,		RedRyder},
	{Loot_WEAPON,		1,		M1014_DZ} //M1014
};
Chainsaws[] = {
	{Loot_WEAPON,		1,		ChainSaw},
	{Loot_WEAPON,		1,		ChainSawB},
	{Loot_WEAPON,		1,		ChainSawG},
	{Loot_WEAPON,		1,		ChainSawP},
	{Loot_WEAPON,		1,		ChainSawR}
};
farmweapons[] = {
	{Loot_WEAPON,		3,		vil_SKS},
	{Loot_GROUP,		5,		shotgunsingleshot},
	{Loot_WEAPON,		2,		CZ550_DZ}, //huntingrifle
	{Loot_GROUP,		0.3,	Chainsaws},
	{Loot_WEAPON,		2,		RedRyder},
	{Loot_WEAPON,		3,		Mosin_DZ}
};
sniperrifles[] = {
	{Loot_WEAPON,		1,		AK_107_PSO},
	{Loot_WEAPON,		0.9,	M4SPR},
	{Loot_WEAPON,		0.9,	M40A3_DZ}, //M40A3
	{Loot_WEAPON,		0.7,	SVD_Gh_DZ}, //SVD_CAMO
	{Loot_WEAPON,		0.7,	SVD_des_EP1},
	{Loot_WEAPON,		0.7,	SVD_DZ}, //SVD
	{Loot_WEAPON,		1,		CZ550_DZ}, //huntingrifle
	{Loot_WEAPON,		0.8,	M24_des_EP1},
	{Loot_WEAPON,		0.8,	M24_DZ}, //M24
	{Loot_WEAPON,		0.7,	BAF_LRR_scoped},
	{Loot_WEAPON,		0.5,	M107_DZ},
	{Loot_WEAPON,		0.5,	KSVK_DZE},
	{Loot_WEAPON,		0.5,	VSS_vintorez},
	{Loot_WEAPON,		0.6,	SCAR_H_LNG_Sniper_SD},
	{Loot_WEAPON,		1,		M14_DZ}, //M14_EP1
	{Loot_WEAPON,		0.7,		DMR_DZ}, //DMR
	{Loot_WEAPON,		0.8,	SCAR_H_LNG_Sniper}, //Mk17 Sniper
	{Loot_WEAPON,		0.6,	M110_NVG_EP1} //M110 NVG
};
submachinegun[] = {
	{Loot_WEAPON,		2,		PDW_DZ}, //UZI_EP1
	{Loot_WEAPON,		1.5,	Bizon_DZ}, //bizon
	{Loot_WEAPON,		1.5,	Sa61_EP1},
	{Loot_WEAPON,		1,		MP5_DZ}, //MP5A5
	{Loot_WEAPON,		1,		Bizon_SD_DZ}, //bizon_silenced
	{Loot_WEAPON,		0.8,	UZI_SD_EP1},
	{Loot_WEAPON,		0.7,	MP5_SD_DZ} //MP5SD
};
assaultrifles[] = {
	{Loot_WEAPON,		0.5,		AK74_Kobra_DZ}, //AKS_74_kobra (stock is slightly different, otherwise identical)
	{Loot_WEAPON,		0.5,		AKS74U_DZ}, //AKS_74_U
	{Loot_WEAPON,		0.1,		AKS_GOLD},
	{Loot_WEAPON,		0.5,		AKM_DZ}, //AK_47_M
	{Loot_WEAPON,		0.5,		AK74_DZ}, //AK_74
	{Loot_WEAPON,		0.3,		FNFAL_DZ}, //FN_FAL
	{Loot_WEAPON,		0.1,		FN_FAL_ANPVS4_DZE}, //FNFAL_ANPVS4_DZ is NV only _DZE is toggleable
	{Loot_WEAPON,		0.5,		G36A_Camo_DZ}, //G36A_camo
	{Loot_WEAPON,		0.5,		G36C_DZ}, //G36C
	{Loot_WEAPON,		0.4,		G36C_camo},
	{Loot_WEAPON,		0.5,		G36K_Camo_DZ}, //G36K_camo
	{Loot_WEAPON,		0.2,		G36_C_SD_camo},
	{Loot_WEAPON,		0.5,		M16A2_DZ}, //M16A2
	//{Loot_WEAPON,		0.2,		M16A2_GL_DZ}, //M16A2GL //added to attachments system
	{Loot_WEAPON,		0.1,		M16A4_ACOG_DZ}, //M16A4_ACG (has slightly different scope)
	{Loot_WEAPON,		0.5,		M4A1_DZ}, //M4A1
	{Loot_WEAPON,		0.4,		M4A1_CCO_DZ}, //M4A1_Aim
	{Loot_WEAPON,		0.1,		M4A1_AIM_SD_camo},
	{Loot_WEAPON,		0.1,		M4A1_HWS_GL_camo},
	{Loot_WEAPON,		0.3,		M4A3_CCO_EP1},
	{Loot_WEAPON,		0.4,		SA58_DZ}, //Sa58P_EP1 (identical), Sa58V_EP1 (different stock)
	{Loot_WEAPON,		0.3,		SA58_CCO_DZ}, //No camo, no grip handle
	{Loot_WEAPON,		0.2,		Sa58V_CCO_EP1}, //Camo with grip handle
	{Loot_WEAPON,		0.3,		SA58_ACOG_DZ}, //No camo, no grip handle
	{Loot_WEAPON,		0.2,		Sa58V_RCO_EP1}, // Camo with grip handle
	{Loot_WEAPON,		0.3,		SA58_RIS_DZ}, //SA58_DZ with different rail
	{Loot_WEAPON,		0.4,		m8_compact},
	{Loot_WEAPON,		0.3,		m8_sharpshooter},
	{Loot_WEAPON,		0.3,		m8_holo_sd},
	{Loot_WEAPON,		0.5,		m8_carbine},
	{Loot_WEAPON,		0.2,		BAF_L85A2_RIS_SUSAT},
	{Loot_WEAPON,		0.3,		L85_Holo_DZ}, //BAF_L85A2_RIS_Holo
	{Loot_WEAPON,		0.1,		M4A1_HWS_GL_SD_Camo},
	{Loot_WEAPON,		0.2,		BAF_L85A2_RIS_ACOG}, //L85A2 ACOG
	//Mk16
	{Loot_WEAPON,		0.2,		SCAR_L_CQC_CCO_SD}, //Mk16 Aimpoint SD 
	{Loot_WEAPON,		0.3,		SCAR_L_CQC}, //Mk16 CQC 
	{Loot_WEAPON,		0.3,		SCAR_L_CQC_Holo}, //Mk16 CQC EOTech 
	{Loot_WEAPON,		0.2,		SCAR_L_CQC_EGLM_Holo}, //Mk16 EGLM EOTech,(40mm)
	{Loot_WEAPON,		0.2,		SCAR_L_STD_EGLM_RCO}, //Mk16 EGLM RCO,(40mm)
	{Loot_WEAPON,		0.3,		SCAR_L_STD_HOLO}, //Mk16 EOTech 
	{Loot_WEAPON,		0.3,		SCAR_L_STD_Mk4CQT}, //Mk16 Mk4CQ/T 
	//Mk17
	{Loot_WEAPON,		0.1,		SCAR_H_CQC_CCO}, //Mk17 Aimpoint
	{Loot_WEAPON,		0.1,		SCAR_H_CQC_CCO_SD}, //Mk17 Aimpoint SD 
	{Loot_WEAPON,		0.1,		SCAR_H_STD_EGLM_Spect} //Mk17 EGLM ACOG,(40mm)	
};
machineguns[] = {
	{Loot_WEAPON,		1.1,	RPK74_DZ}, //RPK_74
	{Loot_WEAPON,		1.1,	M8_SAW},
	{Loot_WEAPON,		1,		Pecheneg_DZ},
	{Loot_WEAPON,		1,		PKM_DZ}, //PK_DZ
	{Loot_WEAPON,		0.9,	L110A1_DZ}, //BAF_L110A1_Aim_DZE scope is slightly different from L110A1_CCO_DZ, otherwise identical
	{Loot_WEAPON,		0.9,		MG36_camo},
	{Loot_WEAPON,		1,		M60A4_EP1_DZE},
	{Loot_WEAPON,		1,		MG36},
	{Loot_WEAPON,		1,		M249_m145_EP1_DZE},
	{Loot_WEAPON,		1,		m240_scoped_EP1_DZE},
	{Loot_WEAPON,		0.8,	M240_DZ},
	{Loot_WEAPON,		0.9,	M249_DZ},
	{Loot_WEAPON,		0.5,	Mk48_DZ}, //Mk_48_DZ (removed, was a duplicate of Mk48_CCO_DZ)
	{Loot_WEAPON,		0.9,	BAF_L86A2_ACOG} //L86A2 ACOG
};
militaryshotguns[] = {
	{Loot_WEAPON,		2,		Saiga12K},
	{Loot_WEAPON,		2,		Remington870_FL_DZ}, //Remington870_lamp
	{Loot_WEAPON,		2,		M1014_DZ}, //M1014
	{Loot_WEAPON,		1,		AA12_PMC} //AA12 Shotgun
};

overwatch_smgs[] = {
	{Loot_WEAPON,		3,		vil_MP5_EOTech},
	{Loot_WEAPON,		2,		vil_MP5SD_EOTech},
	{Loot_WEAPON,		3,		vil_uzi_c},
	{Loot_WEAPON,		3,		vil_uzi},
	{Loot_WEAPON,		2,		vil_uzi_SD},
	{Loot_WEAPON,		3,		vil_uzimini},
	{Loot_WEAPON,		2,		vil_uzimini_SD},
	{Loot_WEAPON,		4,		RH_tec9},
	{Loot_WEAPON,		4,		RH_muzi}
};

overwatch_pistols[] = {
	{Loot_WEAPON,		3,		vil_Tt33},
	{Loot_WEAPON,		3,		Vil_PYA},
	{Loot_WEAPON,		5,		vil_B_HP},
	{Loot_WEAPON,		5,		vil_Glock},
	{Loot_WEAPON,		5,		vil_Glock_o},
	{Loot_WEAPON,		5,		vil_USP},
	{Loot_WEAPON,		5,		vil_USPSD},
	{Loot_WEAPON,		5,		vil_USP45},
	{Loot_WEAPON,		5,		vil_USP45SD},
	{Loot_WEAPON,		3,		DDOPP_X26},
	{Loot_WEAPON,		3,		DDOPP_X26_b},
	{Loot_WEAPON,		3,		DDOPP_X3},
	{Loot_WEAPON,		3,		DDOPP_X3_b},
	{Loot_WEAPON,		2,		RH_deagle},
	{Loot_WEAPON,		2,		RH_Deagleg},
	{Loot_WEAPON,		2,		RH_Deagles},
	{Loot_WEAPON,		2,		RH_Deaglem},
	{Loot_WEAPON,		2,		RH_Deaglemz},
	{Loot_WEAPON,		2,		RH_Deaglemzb},
	{Loot_WEAPON,		3,		RH_anac},
	{Loot_WEAPON,		3,		RH_anacg},
	{Loot_WEAPON,		2,		RH_bull},
	{Loot_WEAPON,		2,		RH_python},
	{Loot_WEAPON,		5,		RH_browninghp},
	{Loot_WEAPON,		5,		RH_p226},
	{Loot_WEAPON,		5,		RH_p226s},
	{Loot_WEAPON,		3,		RH_p38},
	{Loot_WEAPON,		3,		RH_ppk},
	{Loot_WEAPON,		3,		RH_mk22},
	{Loot_WEAPON,		3,		RH_mk22sd},
	{Loot_WEAPON,		3,		RH_mk22v},
	{Loot_WEAPON,		3,		RH_mk22vsd},
	{Loot_WEAPON,		5,		RH_usp},
	{Loot_WEAPON,		5,		RH_uspsd},
	{Loot_WEAPON,		5,		RH_uspm},
	{Loot_WEAPON,		5,		RH_m1911},
	{Loot_WEAPON,		4,		RH_m1911sd},
	{Loot_WEAPON,		6,		RH_m1911old},
	{Loot_WEAPON,		3,		RH_tt33},
	{Loot_WEAPON,		3,		RH_mk2},
	{Loot_WEAPON,		3,		RH_m93r},
	{Loot_WEAPON,		2,		RH_m9},
	{Loot_WEAPON,		2,		RH_m9sd},
	{Loot_WEAPON,		2,		RH_m9c},
	{Loot_WEAPON,		2,		RH_m9csd},
	{Loot_WEAPON,		4,		RH_g18},
	{Loot_WEAPON,		4,		RH_g17},
	{Loot_WEAPON,		2,		RH_g17sd},
	{Loot_WEAPON,		4,		RH_g19},
	{Loot_WEAPON,		4,		RH_g19t},
	{Loot_WEAPON,		1,		RH_vz61}
};

overwatch_rifles_east[] = {
	{Loot_WEAPON,		3,		vil_Abakan},
	{Loot_WEAPON,		3,		vil_Abakan_gp},
	{Loot_WEAPON,		3,		vil_Abakan_P29},
	{Loot_WEAPON,		3,		vil_ak12},
	{Loot_WEAPON,		3,		vil_ak12_ap},
	{Loot_WEAPON,		3,		vil_ak12_gp},
	{Loot_WEAPON,		3,		vil_AEK1},
	{Loot_WEAPON,		3,		vil_AEK2},
	{Loot_WEAPON,		3,		vil_AEK_GL},
	{Loot_WEAPON,		3,		vil_AeK_3},
	{Loot_WEAPON,		3,		vil_AeK_23},
	{Loot_WEAPON,		3,		vil_AeK_3_K},
	{Loot_WEAPON,		3,		vil_APS},
	{Loot_WEAPON,		3,		vil_apssd},
	{Loot_WEAPON,		3,		vil_VAL},
	{Loot_WEAPON,		3,		vil_VAL_C},
	{Loot_WEAPON,		3,		vil_VAL_N},
	{Loot_WEAPON,		3,		vil_type88_1},
	{Loot_WEAPON,		3,		vil_PMI74S},
	{Loot_WEAPON,		3,		vil_Rak74sgl},
	{Loot_WEAPON,		3,		vil_AK_101},
	{Loot_WEAPON,		3,		vil_AK_103},
	{Loot_WEAPON,		3,		vil_AK_105},
	{Loot_WEAPON,		3,		Vil_AK_105_c},
	{Loot_WEAPON,		3,		vil_AK_107},
	{Loot_WEAPON,		3,		Vil_AK_107_c},
	{Loot_WEAPON,		3,		vil_9a91},
	{Loot_WEAPON,		3,		vil_9a91_c},
	{Loot_WEAPON,		3,		vil_9a91_csd},
	{Loot_WEAPON,		3,		vil_vsk94},
	{Loot_WEAPON,		3,		vil_Groza_HG},
	{Loot_WEAPON,		3,		vil_Groza_SC},
	{Loot_WEAPON,		3,		vil_Groza_GL},
	{Loot_WEAPON,		3,		vil_Groza_SD},
	{Loot_WEAPON,		5,		vil_AKS_47},
	{Loot_WEAPON,		5,		vil_AK_47_49},
	{Loot_WEAPON,		5,		vil_AK_47},
	{Loot_WEAPON,		5,		vil_AKMSB},
	{Loot_WEAPON,		5,		vil_AKM},
	{Loot_WEAPON,		4,		vil_AKM_GL},
	{Loot_WEAPON,		5,		vil_AKMS},
	{Loot_WEAPON,		5,		vil_AKMS_GP25},
	{Loot_WEAPON,		5,		vil_AK_47_m1},
	{Loot_WEAPON,		3,		vil_M70},
	{Loot_WEAPON,		3,		vil_M70B},
	{Loot_WEAPON,		3,		vil_M64},
	{Loot_WEAPON,		3,		vil_ASH82},
	{Loot_WEAPON,		3,		vil_AMD},
	{Loot_WEAPON,		3,		vil_AMD63},
	{Loot_WEAPON,		3,		vil_PMI},
	{Loot_WEAPON,		3,		vil_PMIS},
	{Loot_WEAPON,		3,		vil_MPi},
	{Loot_WEAPON,		5,		vil_AKs_74_u},
	{Loot_WEAPON,		5,		vil_AKs_74_u45},
	{Loot_WEAPON,		5,		Vil_AKS_74_UN_kobra},
	{Loot_WEAPON,		5,		Vil_AKS_74_UB},
	{Loot_WEAPON,		5,		vil_AK_74},
	{Loot_WEAPON,		5,		vil_AK_74_gp},
	{Loot_WEAPON,		5,		vil_AK_74_N},
	{Loot_WEAPON,		5,		vil_AKS_74},
	{Loot_WEAPON,		5,		vil_AKS_74_gp},
	{Loot_WEAPON,		5,		vil_AKS_74p},
	{Loot_WEAPON,		5,		vil_AKS_74p_45},
	{Loot_WEAPON,		5,		vil_AK_74P},
	{Loot_WEAPON,		5,		vil_AKS_74p_gp},
	{Loot_WEAPON,		5,		vil_AK_74m},
	{Loot_WEAPON,		5,		vil_AK_74M_N},
	{Loot_WEAPON,		4,		vil_AK_74M_PSO},
	{Loot_WEAPON,		5,		vil_AK_74m_k},
	{Loot_WEAPON,		4,		vil_AK_74m_EOT},
	{Loot_WEAPON,		4,		vil_AK_74m_EOT_Alfa},
	{Loot_WEAPON,		4,		vil_AK_74m_EOT_FSB},
	{Loot_WEAPON,		4,		vil_AK_74m_EOT_FSB_45},
	{Loot_WEAPON,		4,		vil_AK_74m_EOT_FSB_60},
	{Loot_WEAPON,		5,		vil_AK_74m_c},
	{Loot_WEAPON,		5,		vil_AK_74m_p29},
	{Loot_WEAPON,		5,		vil_AK_74m_gp_29},
	{Loot_WEAPON,		5,		vil_AK_74m_gp},
};

overwatch_rifles_west[] = {
	{Loot_WEAPON,		3,		RH_hk416},
	{Loot_WEAPON,		3,		RH_hk416s},
	{Loot_WEAPON,		2,		RH_hk416saim},
	{Loot_WEAPON,		2,		RH_hk416seotech},
	{Loot_WEAPON,		2,		RH_hk416sacog},
	{Loot_WEAPON,		2,		RH_hk416sd},
	{Loot_WEAPON,		2,		RH_hk416sdaim},
	{Loot_WEAPON,		2,		RH_hk416sdeotech},
	{Loot_WEAPON,		2,		RH_hk416aim},
	{Loot_WEAPON,		2,		RH_hk416eotech},
	{Loot_WEAPON,		2,		RH_hk416acog},
	{Loot_WEAPON,		2,		RH_hk416gl},
	{Loot_WEAPON,		2,		RH_hk416glaim},
	{Loot_WEAPON,		2,		RH_hk416gleotech},
	{Loot_WEAPON,		2,		RH_hk416glacog},
	{Loot_WEAPON,		2,		RH_hk416sgl},
	{Loot_WEAPON,		2,		RH_hk416sglaim},
	{Loot_WEAPON,		2,		RH_hk416sgleotech},
	{Loot_WEAPON,		2,		RH_hk416sglacog},
	{Loot_WEAPON,		2,		RH_hk416sdgl},
	{Loot_WEAPON,		2,		RH_hk416sdglaim},
	{Loot_WEAPON,		2,		RH_hk416sdgleotech},
	{Loot_WEAPON,		3,		RH_hk417},
	{Loot_WEAPON,		3,		RH_hk417aim},
	{Loot_WEAPON,		3,		RH_hk417eotech},
	{Loot_WEAPON,		2,		RH_hk417acog},
	{Loot_WEAPON,		2,		RH_hk417sp},
	{Loot_WEAPON,		2,		RH_hk417s},
	{Loot_WEAPON,		2,		RH_hk417saim},
	{Loot_WEAPON,		2,		RH_hk417seotech},
	{Loot_WEAPON,		2,		RH_hk417sacog},
	{Loot_WEAPON,		3,		RH_hk417sd},
	{Loot_WEAPON,		3,		RH_hk417sdaim},
	{Loot_WEAPON,		3,		RH_hk417sdeotech},
	{Loot_WEAPON,		2,		RH_hk417sdacog},
	{Loot_WEAPON,		2,		RH_hk417sdsp},
	{Loot_WEAPON,		2,		RH_hk417sgl},
	{Loot_WEAPON,		2,		RH_hk417sglaim},
	{Loot_WEAPON,		2,		RH_hk417sgleotech},
	{Loot_WEAPON,		2,		RH_hk417sglacog},
	{Loot_WEAPON,		3,		RH_ctar21},
	{Loot_WEAPON,		2,		RH_ctar21glacog},
	{Loot_WEAPON,		3,		RH_ctar21m},
	{Loot_WEAPON,		2,		RH_ctar21mgl},
	{Loot_WEAPON,		3,		RH_star21},
	{Loot_WEAPON,		3,		RH_mas},
	{Loot_WEAPON,		3,		RH_masaim},
	{Loot_WEAPON,		3,		RH_maseotech},
	{Loot_WEAPON,		2,		RH_masacog},
	{Loot_WEAPON,		2,		RH_massd},
	{Loot_WEAPON,		3,		RH_massdaim},
	{Loot_WEAPON,		3,		RH_massdeotech},
	{Loot_WEAPON,		2,		RH_massdacog},
	{Loot_WEAPON,		3,		RH_masb},
	{Loot_WEAPON,		3,		RH_masbaim},
	{Loot_WEAPON,		3,		RH_masbeotech},
	{Loot_WEAPON,		2,		RH_masbacog},
	{Loot_WEAPON,		2,		RH_masbsd},
	{Loot_WEAPON,		3,		RH_masbsdaim},
	{Loot_WEAPON,		2,		RH_masbsdeotech},
	{Loot_WEAPON,		2,		RH_masbsdacog},
	{Loot_WEAPON,		3,		RH_acr},
	{Loot_WEAPON,		3,		RH_acraim},
	{Loot_WEAPON,		3,		RH_acreotech},
	{Loot_WEAPON,		2,		RH_acracog},
	{Loot_WEAPON,		2,		RH_acrgl},
	{Loot_WEAPON,		3,		RH_acrglaim},
	{Loot_WEAPON,		3,		RH_acrgleotech},
	{Loot_WEAPON,		2,		RH_acrglacog},
	{Loot_WEAPON,		3,		RH_acrb},
	{Loot_WEAPON,		3,		RH_acrbaim},
	{Loot_WEAPON,		2,		RH_acrbeotech},
	{Loot_WEAPON,		3,		RH_acrbacog},
	{Loot_WEAPON,		3,		RH_acrbgl},
	{Loot_WEAPON,		3,		RH_acrbglaim},
	{Loot_WEAPON,		2,		RH_acrbgleotech},
	{Loot_WEAPON,		2,		RH_acrbglacog},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_IRN},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_IRN_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_IRN_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_IRN_SD_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_IRN_GL},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_IRN_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_IRN_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_IRN_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_CCO},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_CCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_CCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_CCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_CCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_CCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_CCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_CCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_RCO},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_RCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_RCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_RCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_RCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_RCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_RCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_RCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HWS},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HWS_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HWS_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HWS_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HWS_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HWS_SD_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HWS_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_G33},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_G33_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_G33_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_G33_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_G33_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_G33_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_G33_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_G33_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HAMR},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HAMR_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HAMR_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HAMR_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HAMR_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_WDL_HAMR_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HAMR_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_WDL_HAMR_GL_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_WDL_TWS},
	{Loot_WEAPON,		0.5,		FHQ_ACR_WDL_TWS_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_WDL_TWS_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_WDL_TWS_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_WDL_TWS_GL},
	{Loot_WEAPON,		0.5,		FHQ_ACR_WDL_TWS_GL_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_WDL_TWS_GL_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_WDL_TWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_IRN},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_IRN_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_IRN_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_IRN_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_IRN_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_IRN_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_IRN_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_IRN_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_CCO},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_CCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_CCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_CCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_CCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_CCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_CCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_CCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_RCO},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_RCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_RCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_RCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_RCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_RCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_RCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_RCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HWS},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HWS_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HWS_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HWS_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HWS_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HWS_SD_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HWS_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_G33},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_G33_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_G33_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_G33_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_G33_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_G33_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_G33_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_G33_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HAMR},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HAMR_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HAMR_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HAMR_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HAMR_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_BLK_HAMR_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HAMR_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_BLK_HAMR_GL_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_BLK_TWS},
	{Loot_WEAPON,		0.5,		FHQ_ACR_BLK_TWS_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_BLK_TWS_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_BLK_TWS_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_BLK_TWS_GL},
	{Loot_WEAPON,		0.5,		FHQ_ACR_BLK_TWS_GL_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_BLK_TWS_GL_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_BLK_TWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_IRN},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_IRN_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_IRN_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_IRN_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_IRN_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_IRN_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_IRN_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_IRN_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_CCO},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_CCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_CCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_CCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_CCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_CCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_CCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_CCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_RCO},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_RCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_RCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_RCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_RCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_RCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_RCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_RCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HWS},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HWS_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HWS_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HWS_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HWS_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HWS_SD_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HWS_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_G33},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_G33_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_G33_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_G33_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_G33_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_G33_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_G33_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_G33_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HAMR},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HAMR_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HAMR_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HAMR_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HAMR_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_TAN_HAMR_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HAMR_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_TAN_HAMR_GL_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_TAN_TWS},
	{Loot_WEAPON,		0.5,		FHQ_ACR_TAN_TWS_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_TAN_TWS_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_TAN_TWS_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_TAN_TWS_GL},
	{Loot_WEAPON,		0.5,		FHQ_ACR_TAN_TWS_GL_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_TAN_TWS_GL_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_TAN_TWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_IRN},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_IRN_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_IRN_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_IRN_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_IRN_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_IRN_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_IRN_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_IRN_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_CCO},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_CCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_CCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_CCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_CCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_CCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_CCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_CCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_RCO},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_RCO_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_RCO_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_RCO_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_RCO_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_RCO_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_RCO_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_RCO_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HWS},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HWS_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HWS_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HWS_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HWS_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HWS_SD_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HWS_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HWS_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_G33},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_G33_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_G33_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_G33_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_G33_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_G33_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_G33_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_G33_GL_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HAMR},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HAMR_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HAMR_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HAMR_SD_F},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HAMR_GL},
	{Loot_WEAPON,		3,		FHQ_ACR_SNW_HAMR_GL_F},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HAMR_GL_SD},
	{Loot_WEAPON,		2,		FHQ_ACR_SNW_HAMR_GL_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_SNW_TWS},
	{Loot_WEAPON,		0.5,		FHQ_ACR_SNW_TWS_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_SNW_TWS_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_SNW_TWS_SD_F},
	{Loot_WEAPON,		0.5,		FHQ_ACR_SNW_TWS_GL},
	{Loot_WEAPON,		0.5,		FHQ_ACR_SNW_TWS_GL_F},
	{Loot_WEAPON,		0.2,		FHQ_ACR_SNW_TWS_GL_SD},
	{Loot_WEAPON,		0.2,		FHQ_ACR_SNW_TWS_GL_SD_F},
	{Loot_WEAPON,		5,		vil_AK_nato_m1},
	{Loot_WEAPON,		5,		vil_AK_nato_m80},
	{Loot_WEAPON,		3,		vil_G3a3},
	{Loot_WEAPON,		3,		vil_G3a2},
	{Loot_WEAPON,		3,		vil_G3a4},
	{Loot_WEAPON,		3,		vil_G3a4b},
	{Loot_WEAPON,		3,		vil_G3an},
	{Loot_WEAPON,		3,		vil_G3anb},
	{Loot_WEAPON,		3,		vil_G3ZF},
	{Loot_WEAPON,		3,		vil_G3zfb},
	{Loot_WEAPON,		3,		vil_G3SG1},
	{Loot_WEAPON,		3,		vil_G3sg1b},
	{Loot_WEAPON,		3,		vil_G3TGS},
	{Loot_WEAPON,		3,		vil_G3TGSb},
	{Loot_WEAPON,		3,		vil_AG3},
	{Loot_WEAPON,		3,		vil_AG3EOT},
	{Loot_WEAPON,		3,		vil_HK417s},
	{Loot_WEAPON,		3,		vil_Fal},
	{Loot_WEAPON,		3,		vil_Fal_Para},
	{Loot_WEAPON,		3,		vil_sg540},
	{Loot_WEAPON,		3,		vil_sg542},
	{Loot_WEAPON,		3,		vil_sg542f},
	{Loot_WEAPON,		3,		vil_Insas},
	{Loot_WEAPON,		3,		vil_M16A1},
	{Loot_WEAPON,		3,		VIL_M4},
	{Loot_WEAPON,		3,		vil_M4_EOT},
	{Loot_WEAPON,		3,		VIL_M4_aim},
	{Loot_WEAPON,		3,		vil_HK33},
	{Loot_WEAPON,		4,		vil_Galil},
	{Loot_WEAPON,		4,		vil_Galil_arm},
	{Loot_WEAPON,		3,		vil_G36KVA4},
	{Loot_WEAPON,		3,		vil_G36KA4},
	{Loot_WEAPON,		4,		vil_G36E},
	{Loot_WEAPON,		3,		vil_G36a2},
	{Loot_WEAPON,		4,		vil_AG36},
	{Loot_WEAPON,		3,		vil_AG36A2},
	{Loot_WEAPON,		3,		vil_AG36KV},
	{Loot_WEAPON,		3,		vil_AG36KA4},
	{Loot_WEAPON,		3,		vil_G36VA4},
	{Loot_WEAPON,		3,		vil_G36VA4Eot},
	{Loot_WEAPON,		3,		vil_G36KVZ},
	{Loot_WEAPON,		3,		vil_G36KSK},
	{Loot_WEAPON,		3,		vil_G36KSKdes},
	{Loot_WEAPON,		3,		vil_G36KSKdesES},
	{Loot_WEAPON,		4,		vil_G36CC},
	{Loot_WEAPON,		3,		vil_G36KSKES},
	{Loot_WEAPON,		3,		vil_G36KES},
	{Loot_WEAPON,		3,		vil_G36KV3},
	{Loot_WEAPON,		3,		vil_G36KV3Des},
	{Loot_WEAPON,		4,		vil_HK416_Aim},
	{Loot_WEAPON,		4,		vil_HK416_IS},
	{Loot_WEAPON,		4,		vil_HK416_EOT},
	{Loot_WEAPON,		4,		vil_HK416_GL},
	{Loot_WEAPON,		3,		VIL_HK416_EDR}
};

overwatch_rifles[] = {
	{Loot_GROUP,		2,		overwatch_rifles_east},
	{Loot_GROUP,		1,		overwatch_rifles_west}
};

overwatch_snipers[] = {
	{Loot_WEAPON,		3,		vil_PSL1},
	{Loot_WEAPON,		3,		vil_M76},
	{Loot_WEAPON,		3,		vil_M91},
	{Loot_WEAPON,		4,		vil_SR25},
	{Loot_WEAPON,		3,		vil_M110},
	{Loot_WEAPON,		4,		vil_SVU_A},
	{Loot_WEAPON,		4,		vil_SVU},
	{Loot_WEAPON,		2,		vil_VSS_PSO},
	{Loot_WEAPON,		2,		vil_VSS_N},
	{Loot_WEAPON,		2,		FHQ_MSR_DESERT},
	{Loot_WEAPON,		1,		FHQ_MSR_SD_DESERT},
	{Loot_WEAPON,		1,		FHQ_MSR_NV_DESERT},
	{Loot_WEAPON,		1,		FHQ_MSR_NV_SD_DESERT},
	{Loot_WEAPON,		0.1,		FHQ_MSR_TWS_DESERT},
	{Loot_WEAPON,		0.1,		FHQ_MSR_TWS_SD_DESERT},
	{Loot_WEAPON,		3,		FHQ_RSASS_TAN},
	{Loot_WEAPON,		0.5,		FHQ_RSASS_TWS_TAN},
	{Loot_WEAPON,		1,		FHQ_RSASS_SD_TAN},
	{Loot_WEAPON,		0.1,		FHQ_RSASS_TWS_SD_TAN},
	{Loot_WEAPON,		3,		FHQ_XM2010_DESERT},
	{Loot_WEAPON,		3,		FHQ_XM2010_SD_DESERT},
	{Loot_WEAPON,		3,		FHQ_XM2010_NV_DESERT},
	{Loot_WEAPON,		3,		FHQ_XM2010_NV_SD_DESERT},
	{Loot_WEAPON,		0.1,		FHQ_XM2010_TWS_DESERT},
	{Loot_WEAPON,		0.1,		FHQ_XM2010_TWS_SD_DESERT},
	{Loot_WEAPON,		3,		FHQ_XM2010_WDL_CAMO},
	{Loot_WEAPON,		5,		RH_m14},
	{Loot_WEAPON,		4,		RH_m14acog},
	{Loot_WEAPON,		4,		RH_m14aim},
	{Loot_WEAPON,		4,		RH_m14eot},
	{Loot_WEAPON,		5,		RH_m21},
	{Loot_WEAPON,		5,		RH_sc2},
	{Loot_WEAPON,		4,		RH_sc2acog},
	{Loot_WEAPON,		4,		RH_sc2aim},
	{Loot_WEAPON,		4,		RH_sc2eot},
	{Loot_WEAPON,		4,		RH_sc2shd},
	{Loot_WEAPON,		4,		RH_sc2sp},
	{Loot_WEAPON,		5,		RH_m1s},
	{Loot_WEAPON,		4,		RH_m1sacog},
	{Loot_WEAPON,		4,		RH_m1saim},
	{Loot_WEAPON,		4,		RH_m1seot},
	{Loot_WEAPON,		4,		RH_m1sshd},
	{Loot_WEAPON,		4,		RH_m1ssp},
	{Loot_WEAPON,		4,		RH_m1st},
	{Loot_WEAPON,		4,		RH_m1stacog},
	{Loot_WEAPON,		4,		RH_m1staim},
	{Loot_WEAPON,		4,		RH_m1steot},
	{Loot_WEAPON,		4,		RH_m1stshd},
	{Loot_WEAPON,		4,		RH_m1stsp},
	{Loot_WEAPON,		2,		vil_SR25SD},
	{Loot_WEAPON,		2,		vil_M110sd},
	{Loot_WEAPON,		3,		vil_M21},
	{Loot_WEAPON,		3,		vil_M21G},
	{Loot_WEAPON,		4,		vil_m40a3},
	{Loot_WEAPON,		4,		vil_M24b},
	{Loot_WEAPON,		5,		vil_M14},
	{Loot_WEAPON,		5,		vil_M14G},
	{Loot_WEAPON,		0.1,		USSR_cheytacM200},
	{Loot_WEAPON,		0.1,		USSR_cheytacM200_sd},
	{Loot_WEAPON,		4,		vil_SVD_63},
	{Loot_WEAPON,		4,		vil_SVD_N},
	{Loot_WEAPON,		4,		vil_SVD_S},
	{Loot_WEAPON,		4,		vil_SVD_M},
	{Loot_WEAPON,		3,		vil_SVD_P21},
	{Loot_WEAPON,		2,		vil_SVDK},
	{Loot_WEAPON,		3,		vil_SV_98},
	{Loot_WEAPON,		3,		vil_SV_98_69},
	{Loot_WEAPON,		3,		vil_SV_98_SD}
};
overwatch_machines[] = {
	{Loot_WEAPON,		3,		skavil_M60},
	{Loot_WEAPON,		3,		skavil_M60e3},
	{Loot_WEAPON,		3,		vil_Mg3},
	{Loot_WEAPON,		3,		vil_M249_Para},
	{Loot_WEAPON,		3,		vil_Minimi},
	{Loot_WEAPON,		3,		vil_FnMag},
	{Loot_WEAPON,		3,		vil_M240_B},
	{Loot_WEAPON,		3,		vil_MG4},
	{Loot_WEAPON,		3,		vil_MG4E},
	{Loot_WEAPON,		3,		vil_Insas_lmg},
	{Loot_WEAPON,		3,		vil_PKP},
	{Loot_WEAPON,		3,		vil_PKP_EOT},
	{Loot_WEAPON,		3,		vil_PK},
	{Loot_WEAPON,		3,		vil_zastava_m84},
	{Loot_WEAPON,		3,		vil_PKM_N},
	{Loot_WEAPON,		3,		vil_PKM},
	{Loot_WEAPON,		3,		vil_RPK},
	{Loot_WEAPON,		3,		vil_RPK75},
	{Loot_WEAPON,		3,		vil_RPK75_Romania},
	{Loot_WEAPON,		3,		vil_RPK75_M72},
	{Loot_WEAPON,		3,		vil_RPD},
	{Loot_WEAPON,		3,		vil_RPK74},
	{Loot_WEAPON,		3,		vil_RPK74M_P29},
	{Loot_WEAPON,		3,		vil_RPK74M},
	{Loot_WEAPON,		3,		vil_RPK74M_N},
	{Loot_WEAPON,		0.1,		vil_CG84T},
	{Loot_WEAPON,		0.05,		vil_Vikhr},
	{Loot_WEAPON,		0.05,		vil_Panzerfaust3}
};
