class Category_1055 {				
class 30Rnd_556x45_Stanag {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {6,"ItemSilverBar"};	};
class 30Rnd_556x45_StanagSD {	type = "trade_items";	buy[] = {1,"ItemSilverBar10oz"};	sell[] = {8,"ItemSilverBar"};	};
class 30Rnd_556x45_G36 {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {6,"ItemSilverBar"};	};
class 30Rnd_556x45_G36SD {	type = "trade_items";	buy[] = {1,"ItemSilverBar10oz"};	sell[] = {8,"ItemSilverBar"};	};
class 20Rnd_762x51_FNFAL {	type = "trade_items";	buy[] = {2,"ItemSilverBar10oz"};	sell[] = {1,"ItemSilverBar10oz"};	};
class 30Rnd_545x39_AK {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_545x39_AKSD {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_762x39_AK47 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_762x39_SA58 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
};				
class Category_1056 {				
class 100Rnd_556x45_M249 {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class 200Rnd_556x45_M249 {	type = "trade_items";	buy[] = {6,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class 100Rnd_762x51_M240 {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class 50Rnd_762x54_UK59 {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class 75Rnd_545x39_RPK {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class 75Rnd_762x39_RPK {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
class 100Rnd_762x54_PK {	type = "trade_items";	buy[] = {6,"ItemGoldBar"};	sell[] = {3,"ItemGoldBar"};	};
};				
class Category_1057 {				
class 15Rnd_9x19_M9 {	type = "trade_items";	buy[] = {6,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class 15Rnd_9x19_M9SD {	type = "trade_items";	buy[] = {6,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class 17Rnd_9x19_glock17 {	type = "trade_items";	buy[] = {6,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class 17Rnd_9x19_glock17SD {	type = "trade_items";	buy[] = {6,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class 6Rnd_45ACP {	type = "trade_items";	buy[] = {3,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 7Rnd_45ACP_1911 {	type = "trade_items";	buy[] = {3,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 8Rnd_9x18_Makarov {	type = "trade_items";	buy[] = {3,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 8Rnd_9x18_MakarovSD {	type = "trade_items";	buy[] = {6,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
};				
class Category_1058 {				
class 1Rnd_Bolt_Tranquilizer {	type = "trade_items";	buy[] = {2,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
class 1Rnd_Bolt_Explosive {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {8,"ItemSilverBar"};	};
class 12Rnd_Quiver_Wood {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 350Rnd_BB_Magazine {	type = "trade_items";	buy[] = {2,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
class 2Rnd_12Gauge_Buck {	type = "trade_items";	buy[] = {1,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
class 2Rnd_12Gauge_Slug {	type = "trade_items";	buy[] = {1,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
class 8Rnd_12Gauge_Slug {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 8Rnd_12Gauge_Buck {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 15Rnd_W1866_Slug {	type = "trade_items";	buy[] = {2,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
class 10Rnd_303British {	type = "trade_items";	buy[] = {2,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
class 5Rnd_762x54_Mosin {	type = "trade_items";	buy[] = {2,"ItemSilverBar"};	sell[] = {1,"ItemSilverBar"};	};
};				
class Category_1059 {				
class 5Rnd_17HMR {	type = "trade_items";	buy[] = {6,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 5Rnd_762x51_M24 {	type = "trade_items";	buy[] = {1,"ItemGoldBar"};	sell[] = {6,"ItemSilverBar"};	};
class 20Rnd_762x51_DMR {	type = "trade_items";	buy[] = {4,"ItemGoldBar"};	sell[] = {1,"ItemGoldBar"};	};
class 10Rnd_762x54_SVD {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
};				
class Category_1060 {				
class 20Rnd_B_765x17_Ball {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_9x19_UZI {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_9x19_UZI_SD {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_9x19_MP5 {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 30Rnd_9x19_MP5SD {	type = "trade_items";	buy[] = {4,"ItemSilverBar"};	sell[] = {2,"ItemSilverBar"};	};
class 64Rnd_9x19_Bizon {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 64Rnd_9x19_SD_Bizon {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
};				
class Category_1061 {				
class vil_17Rnd_9x19_PYA {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_bhp_mag {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class DDOPP_1Rnd_X26 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class DDOPP_3Rnd_X3 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_10Rnd_22LR_mk2 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_12Rnd_45cal_usp {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_13Rnd_9x19_bhp {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_15Rnd_9x19_usp {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_15Rnd_9x19_uspsd {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_17Rnd_9x19_g17 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_17Rnd_9x19_g17SD {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_19Rnd_9x19_g18 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_30Rnd_9x19_tec {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_32Rnd_9x19_Muzi {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_6Rnd_357_Mag {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_6Rnd_44_Mag {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_7Rnd_32cal_ppk {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_7Rnd_50_AE {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_8Rnd_45cal_m1911 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_8Rnd_762_tt33 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_8Rnd_9x19_Mk {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_8Rnd_9x19_Mksd {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class RH_8Rnd_9x19_P38 {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_10Rnd_Mauser {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_32Rnd_uzi {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_32Rnd_UZI_SD {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_usp45_mag {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_usp45sd_mag {	type = "trade_items";	buy[] = {5,"ItemSilverBar"};	sell[] = {3,"ItemSilverBar"};	};
class vil_10Rnd_762x39_SKS {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
};				
class Category_1062 {				
class FHQ_rem_30Rnd_680x43_ACR {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class FHQ_rem_30Rnd_680x43_ACR_SD {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_9x18_aps {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_9x18_apsSD {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_9x39_SP6_OC {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_9x39_SP6_VAL {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_9x39_SP6ns_OC {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class VIL_30Rnd_556x45_AK {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class Vil_30Rnd_556x45_HK {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_30Rnd_762x39_AKSD {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class Vil_35Rnd_556x45_G {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_40Rnd_762x39_AK47 {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_45Rnd_545x39_AK {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class Vil_50Rnd_556x45_G {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_60Rnd_545x39_AK {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_75Rnd_762x39_AK47 {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_8Rnd_TT {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_556x45_IN {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_556x45_SG {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_762x51_G3 {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class vil_20Rnd_762x51_SG {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class RH_20Rnd_762x51_hk417 {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class RH_20Rnd_762x51_SD_hk417 {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class FHQ_rem_20Rnd_762x51_PMAG_NT {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class FHQ_rem_20Rnd_762x51_PMAG_NT_SD {	type = "trade_items";	buy[] = {7,"ItemSilverBar"};	sell[] = {5,"ItemSilverBar"};	};
class FHQ_rem_5Rnd_300Win_XM2010_NT {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class FHQ_rem_5Rnd_300Win_XM2010_NT_SD {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class FHQ_rem_7Rnd_338Lapua_MSR_NT {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class FHQ_rem_7Rnd_338Lapua_MSR_NT_SD {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class RH_20Rnd_32cal_vz61 {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class RH_20Rnd_9x19_M93 {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class USSR_5Rnd_408 {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class vil_100Rnd_762x39_RPD {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class vil_10Rnd_762x54_SV {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class vil_10Rnd_PSL {	type = "trade_items";	buy[] = {5,"ItemGoldBar"};	sell[] = {2,"ItemGoldBar"};	};
class vil_10Rnd_SVDK {	type = "trade_items";	buy[] = {3,"ItemGoldBar"};	sell[] = {1,"ItemGoldBar"};	};
};				
