class Category_1063 {				
class 100Rnd_762x51_M240 {	type = "trade_items";	buy[] = {1,"ItemGoldBar10oz"};	sell[] = {4,"ItemGoldBar"};	};
class 30Rnd_556x45_StanagSD {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 20Rnd_762x51_B_SCAR {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 20Rnd_762x51_SB_SCAR {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 20Rnd_762x51_FNFAL {	type = "trade_items";	buy[] = {4,"ItemSilverBar10oz"};	sell[] = {2,"ItemSilverBar10oz"};	};
class 20Rnd_762x51_DMR {	type = "trade_items";	buy[] = {4,"ItemGoldBar"};	sell[] = {1,"ItemGoldBar"};	};
class 5Rnd_86x70_L115A1 {	type = "trade_items";	buy[] = {1,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar"};	};
class 10Rnd_127x99_m107 {	type = "trade_items";	buy[] = {-1,"ItemGoldBar"};	sell[] = {6,"ItemGoldBar"};	};
class MAAWS_HEAT {	type = "trade_items";	buy[] = {-1,"ItemGoldBar"};	sell[] = {8,"ItemGoldBar"};	};
};				
class Category_1064 {				
class Skin_Bandit1_DZ {	type = "trade_items";	buy[] = {2,"ItemSilverBar10oz"};	sell[] = {1,"ItemSilverBar10oz"};	};
class Skin_Bandit2_DZ {	type = "trade_items";	buy[] = {2,"ItemSilverBar10oz"};	sell[] = {1,"ItemSilverBar10oz"};	};
class Skin_BanditW1_DZ {	type = "trade_items";	buy[] = {2,"ItemSilverBar10oz"};	sell[] = {1,"ItemSilverBar10oz"};	};
class Skin_BanditW2_DZ {	type = "trade_items";	buy[] = {2,"ItemSilverBar10oz"};	sell[] = {1,"ItemSilverBar10oz"};	};
class Skin_GUE_Commander_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_GUE_Soldier_2_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_GUE_Soldier_CO_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_GUE_Soldier_Crew_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_GUE_Soldier_Sniper_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Ins_Soldier_GL_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_TK_INS_Soldier_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_TK_INS_Warlord_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_RU_Soldier_Crew_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_TK_INS_Soldier_AR_EP1_DZ{	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_TK_GUE_Soldier_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_RU_Soldier_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_RU_Soldier_Officer_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_RUS_Soldier1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_RUS_Commander_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_MVD_Soldier_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Ins_Soldier_2_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Ins_Commander_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Ins_Soldier_Crew_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_CDF_Soldier_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
};				
class Category_1065 {				
class Skin_CZ_Special_Forces_GL_DES_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Drake_Light_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Soldier_Sniper_PMC_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_OHara_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_Rodriguez_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_CZ_Soldier_Sniper_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Graves_Light_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Soldier_Bodyguard_AA12_PMC_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Camo1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Rocket_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Sniper1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Soldier1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_Soldier_TL_PMC_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_USMC_Soldier_Officer_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_USMC_Soldier_MG_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_USMC_Soldier_Pilot_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_TL_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_R_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_Sapper_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_Marksman_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_FR_Assault_R_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_CZ_Soldier_SL_DES_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_US_Soldier_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_UN_CDF_Soldier_Guard_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_UN_CDF_Soldier_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_GER_Soldier_TL_EP1_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_BAF_Soldier_Officer_MTP_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class Skin_BAF_Soldier_N_MTP_DZ {	type = "trade_items";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
};				
class Category_1066 {				
class G36_C_SD_camo {	type = "trade_weapons";	buy[] = {1,"ItemGoldBar10oz"};	sell[] = {5,"ItemGoldBar"};	};
class M4A1_AIM_SD_camo {	type = "trade_weapons";	buy[] = {1,"ItemGoldBar10oz"};	sell[] = {5,"ItemGoldBar"};	};
class FNFAL_DZ {	type = "trade_weapons";	buy[] = {8,"ItemGoldBar"};	sell[] = {4,"ItemGoldBar"};	};
class FN_FAL_ANPVS4_DZE {	type = "trade_weapons";	buy[] = {3,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class SCAR_H_LNG_Sniper {	type = "trade_weapons";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class SCAR_H_LNG_Sniper_SD {	type = "trade_weapons";	buy[] = {5,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class M110_NVG_EP1 {	type = "trade_weapons";	buy[] = {7,"ItemGoldBar10oz"};	sell[] = {4,"ItemGoldBar10oz"};	};
class DMR_DZ {	type = "trade_weapons";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class BAF_LRR_scoped {	type = "trade_weapons";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class M240_DZ {	type = "trade_weapons";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class Mk48_DZ {	type = "trade_weapons";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class Mk48_CCO_DZ {	type = "trade_weapons";	buy[] = {2,"ItemGoldBar10oz"};	sell[] = {9,"ItemGoldBar"};	};
class m107_DZ {	type = "trade_weapons";	buy[] = {-1,"ItemGoldBar"};	sell[] = {7,"ItemGoldBar10oz"};	};
class MAAWS {	type = "trade_weapons";	buy[] = {-1,"ItemGoldBar"};	sell[] = {9,"ItemGoldBar10oz"};	};
};				
class Category_1067 {				
class 100Rnd_762x51_M240 {	type = "trade_items";	buy[] = {1,"ItemGoldBar10oz"};	sell[] = {4,"ItemGoldBar"};	};
class 30Rnd_556x45_StanagSD {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 20Rnd_762x51_B_SCAR {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 20Rnd_762x51_SB_SCAR {	type = "trade_items";	buy[] = {8,"ItemSilverBar"};	sell[] = {4,"ItemSilverBar"};	};
class 20Rnd_762x51_FNFAL {	type = "trade_items";	buy[] = {4,"ItemSilverBar10oz"};	sell[] = {2,"ItemSilverBar10oz"};	};
class 20Rnd_762x51_DMR {	type = "trade_items";	buy[] = {4,"ItemGoldBar"};	sell[] = {1,"ItemGoldBar"};	};
class 5Rnd_86x70_L115A1 {	type = "trade_items";	buy[] = {1,"ItemGoldBar10oz"};	sell[] = {3,"ItemGoldBar"};	};
class 10Rnd_127x99_m107 {	type = "trade_items";	buy[] = {-1,"ItemGoldBar"};	sell[] = {6,"ItemGoldBar"};	};
class MAAWS_HEAT {	type = "trade_items";	buy[] = {-1,"ItemGoldBar"};	sell[] = {8,"ItemGoldBar"};	};
};				
class Category_1068 {				
class Mi17_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemBriefcase100oz"};	sell[] = {1,"ItemBriefcase100oz"};	};
class UH1H_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemBriefcase100oz"};	sell[] = {1,"ItemBriefcase100oz"};	};
class UH1Y_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemBriefcase100oz"};	sell[] = {1,"ItemBriefcase100oz"};	};
class UH60M_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemBriefcase100oz"};	sell[] = {1,"ItemBriefcase100oz"};	};
class MH60S_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemBriefcase100oz"};	sell[] = {1,"ItemBriefcase100oz"};	};
class CH_47F_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemBriefcase100oz"};	sell[] = {2,"ItemBriefcase100oz"};	};
class CH53_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemBriefcase100oz"};	sell[] = {2,"ItemBriefcase100oz"};	};
class MH60S {	type = "trade_any_vehicle";	buy[] = {7,"ItemBriefcase100oz"};	sell[] = {6,"ItemBriefcase100oz"};	};
class UH60M_EP1 {	type = "trade_any_vehicle";	buy[] = {7,"ItemBriefcase100oz"};	sell[] = {6,"ItemBriefcase100oz"};	};
class Ka60_PMC {	type = "trade_any_vehicle";	buy[] = {9,"ItemBriefcase100oz"};	sell[] = {6,"ItemBriefcase100oz"};	};
};				
class Category_1069 {				
class LandRover_MG_TK_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {1,"ItemBriefcase100oz"};	sell[] = {5,"ItemGoldBar10oz"};	};
class LandRover_Special_CZ_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {2,"ItemBriefcase100oz"};	sell[] = {8,"ItemGoldBar10oz"};	};
class UAZ_MG_TK_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {8,"ItemGoldBar10oz"};	sell[] = {5,"ItemGoldBar10oz"};	};
class GAZ_Vodnik_DZE {	type = "trade_any_vehicle";	buy[] = {2,"ItemBriefcase100oz"};	sell[] = {8,"ItemGoldBar10oz"};	};
class HMMWV_M998A2_SOV_DES_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {2,"ItemBriefcase100oz"};	sell[] = {8,"ItemGoldBar10oz"};	};
class HMMWV_M1151_M2_CZ_DES_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {2,"ItemBriefcase100oz"};	sell[] = {8,"ItemGoldBar10oz"};	};
class BRDM2_HQ_Gue  {	type = "trade_any_vehicle";	buy[] = {8,"ItemBriefcase100oz"};	sell[] = {5,"ItemBriefcase100oz"};	};
class T34 {	type = "trade_any_vehicle";	buy[] = {12,"ItemRuby"};	sell[] = {10,"ItemRuby"};	};
};				
class Category_1070 {				
class Pickup_PK_TK_GUE_EP1_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Pickup_PK_GUE_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Pickup_PK_INS_DZE {	type = "trade_any_vehicle";	buy[] = {4,"ItemGoldBar10oz"};	sell[] = {1,"ItemGoldBar10oz"};	};
class Offroad_DSHKM_Gue_DZE {	type = "trade_any_vehicle";	buy[] = {6,"ItemGoldBar10oz"};	sell[] = {2,"ItemGoldBar10oz"};	};
class ArmoredSUV_PMC_DZE {	type = "trade_any_vehicle";	buy[] = {3,"ItemBriefcase100oz"};	sell[] = {1,"ItemBriefcase100oz"};	};
};				
